apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: container-course-week01

resources:
  - namespace.yaml
  - gallery-configmap.yaml
  - student-almsid-deployment.yaml
  - student-emmzi55-deployment.yaml
  - student-jlgore-deployment.yaml
  - student-omar-masood-deployment.yaml
  - student-otajon99-deployment.yaml
